apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-node

spec:
  replicas: 1

  selector:
    matchLabels:
      app: app-node

  template:
    metadata:
      labels:
        app: app-node

    spec:
      containers:
      - name: app-node
        image: adibush/app-node:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 3000
