apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-node

spec:
  replicas: 2

  selector:
    matchLabels:
      app: app-node

  template:
    metadata:
      labels:
        app: app-node

    spec:
      containers:
        - name: app-node
          image: adibush/app-node:7538da2dd99d48f547972d5e5f38d7a4f5f72f01
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
