apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-node

spec:
  replicas: 1

  selector:
    matchLabels:
      app: app-node

  template:
    metadata:
      labels:
        app: app-node

    spec:
      containers:
        - name: app-node
          image: adibush/app-node:861192dc9eea15140ed84ba1226eaa0b9322784a
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
