apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-node

spec:
  replicas: 1

  selector:
    matchLabels:
      app: app-node

  template:
    metadata:
      labels:
        app: app-node

    spec:
      containers:
        - name: app-node
          image: adibush/app-node:9feb30e98da89f975a331c043d12c3c009b6580b
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
